apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphql-server
  name: graphql-server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: graphql-server
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-server
  labels:
    app: graphql-server
spec:
  selector:
    matchLabels:
      app: graphql-server
  replicas: 1
  template:
    metadata:
      labels:
        app: graphql-server
    spec:
      restartPolicy: Always
      containers:
        - name: graphql-server
          image: {{ .Values.graphqlServer.imageName }}:{{ .Values.buildTag }}
          command: ["/usr/likedao/bin/graphql-server"]
          ports:
            - containerPort: 8080
          env:
            - name: GIN_MODE
              value: release
            - name: GRAPHQL_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config
                  key: GRAPHQL_SENTRY_DSN
            - name: GRAPHQL_SENTRY_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config
                  key: GRAPHQL_SENTRY_ENVIRONMENT
            - name: SERVER_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config
                  key: SERVER_DATABASE_URL
            - name: BDJUNO_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config
                  key: BDJUNO_DATABASE_URL
            - name: SERVER_DATABASE_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config
                  key: SERVER_DATABASE_SCHEMA
            - name: BDJUNO_DATABASE_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config
                  key: BDJUNO_DATABASE_SCHEMA
            - name: SERVER_DATABASE_POOL_SIZE
              value: {{ .Values.graphqlServer.serverDatabase.poolSize | quote }}
            - name: BDJUNO_DATABASE_POOL_SIZE
              value: {{ .Values.graphqlServer.bdjunoDatabase.poolSize | quote }}
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: graphql-server-config
type: Opaque
data:
  SERVER_DATABASE_URL: {{ .Values.graphqlServer.serverDatabase.url | b64enc }}
  SERVER_DATABASE_SCHEMA: {{ .Values.graphqlServer.serverDatabase.schema | b64enc }}
  BDJUNO_DATABASE_URL: {{ .Values.graphqlServer.bdjunoDatabase.url | b64enc }}
  BDJUNO_DATABASE_SCHEMA: {{ .Values.graphqlServer.bdjunoDatabase.schema | b64enc }}
  GRAPHQL_SENTRY_DSN: {{ .Values.graphqlServer.sentry.dsn | b64enc }}
  GRAPHQL_SENTRY_ENVIRONMENT: {{ .Values.graphqlServer.sentry.environment | b64enc }}