chain:
    bech32_prefix: like
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - mint
        - slashing
        - staking
        - distribution
        - iscn
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://localhost:26657
            max_connections: 20
        grpc:
            address: localhost:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    average_block_time: 5s
database:
    name: bdjuno
    host: bdjuno-db
    port: 5432
    user: bdjuno
    password: bdjuno
    schema: bdjuno
    max_open_connections: 1
    max_idle_connections: 1
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
actions:
    port: 3000
